source 'https://github.com/CocoaPods/Specs.git'
source 'git@bitbucket.org:codedazur/cda-ios-pods.git'

target 'CDASyncService_Example' do
  pod "CDASyncService", :path => "../"
end

target 'CDASyncService_Tests' do
  pod "CDASyncService", :path => "../"
end
